# Generated by Django 5.2.10 on 2026-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_col', models.CharField(max_length=10)),
                ('bet_type', models.CharField(max_length=20)),
                ('total_bet_yen', models.IntegerField()),
                ('total_return_yen', models.IntegerField()),
                ('n_bets', models.IntegerField()),
                ('n_hits', models.IntegerField()),
                ('hit_rate', models.FloatField()),
                ('roi', models.FloatField()),
                ('kaisai_date', models.CharField(db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
