# Generated by Django 5.2.10 on 2026-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_index=True, max_length=20)),
                ('kaisai_date', models.CharField(db_index=True, max_length=8)),
                ('venue', models.CharField(db_index=True, max_length=10)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, default='', max_length=5)),
                ('weather', models.CharField(blank=True, default='', max_length=10)),
                ('baba', models.CharField(blank=True, default='', max_length=10)),
                ('axis_col', models.CharField(db_index=True, max_length=10)),
                ('axis_mark', models.CharField(blank=True, default='', max_length=10)),
                ('bet_type', models.CharField(db_index=True, max_length=20)),
                ('total_bet_yen', models.IntegerField()),
                ('total_return_yen', models.FloatField()),
                ('n_bets', models.IntegerField()),
                ('n_hits', models.IntegerField()),
                ('hit_rate', models.FloatField()),
                ('roi', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kaisai_date', 'venue'], name='dashboard_p_kaisai__ddb476_idx'), models.Index(fields=['kaisai_date', 'venue', 'axis_col'], name='dashboard_p_kaisai__cb9340_idx'), models.Index(fields=['kaisai_date', 'venue', 'bet_type'], name='dashboard_p_kaisai__e1bdda_idx')],
            },
        ),
    ]
